spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    driver:
      class: org.h2.Driver
    hikari:
      pool-name: alert
      connection-timeout: 60000
      minimum-idle: 3
      maximum-pool-size: 100
      leak-detection-threshold: 60000
      connection-init-sql: SELECT 1 FROM DUAL
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: true
    baselineOnMigrate: true
    baselineVersion: 0
    url: ${spring.datasource.url}
    user: sa
    password:
  application:
    name: address-api

address-api:
  integration:
    google-maps:
      key: 'AIzaSyCj0cY2yEvVfYhAaTz3-P2MW-YRKmhz5Uw'