CREATE TABLE ADDRESS
(

    ID            BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    STREET_NAME   VARCHAR(255),
    NUMBER        VARCHAR(5),
    COMPLEMENT    VARCHAR(255),
    NEIGHBOURHOOD VARCHAR(255),
    CITY          VARCHAR(255),
    STATE         VARCHAR(255),
    COUNTRY       VARCHAR(255),
    ZIPCODE       VARCHAR(255),
    LATITUDE      VARCHAR(30),
    LONGITUDE     VARCHAR(30)

);